services:
  ollama:
    image: ollama/ollama:latest
    env_file: .env
    ports: ["127.0.0.1:11434:11434"]
    volumes: ["ollama:/root/.ollama"]

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["127.0.0.1:6333:6333"]
    volumes: ["qdrant:/qdrant/storage"]

  api:
    build: ./api
    env_file: .env
    ports: ["127.0.0.1:8000:8000"]
    volumes: ["./data:/app/data"]
    depends_on: [ollama, qdrant]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE_URL=http://api:8000/v1
      - OPENAI_API_KEY=${AUTH_TOKEN:-demo-key}
    ports: ["127.0.0.1:3000:8080"]
    depends_on: [api]

volumes:
  ollama: {}
  qdrant: {}
