services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /opt/rag/ollama:/root/.ollama
    environment:
      # Modelle länger im Speicher halten
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    volumes:
      - /opt/rag/chroma:/chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
    restart: unless-stopped

  api:
    build: ./api
    container_name: rag-api
    env_file: .env
    depends_on:
      - ollama
      - chroma
    volumes:
      - /opt/rag/data:/app/data
    ports:
      - "8000:8000"
    environment:
      - ANONYMIZED_TELEMETRY=false
    # Nutzt den CMD aus dem Dockerfile: uvicorn main:app ...
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; urllib.request.urlopen(\"http://localhost:8000/health\").read()' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 5
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - RAG_API_URL=http://api:8000
      - WEBUI_AUTH=false
    depends_on:
      - api
    ports:
      - "3000:8080"
    restart: unless-stopped

